apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
  labels:
    app: miiingle
    {{- include "user-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: miiingle
  template:
    metadata:
      labels:
        app: miiingle
    spec:
      containers:
        - name: application
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          env:
            - name: TRACING_ZIPKIN_HTTP_URL
              value: "{{ .Values.env.TRACING_ZIPKIN_HTTP_URL }}"
            - name: SERVER_PORT
              value: "{{ .Values.env.SERVER_PORT }}"
            - name: DATASOURCES_DEFAULT_URL
              value: "jdbc:postgresql://{{ .Values.config.rds.host }}:{{ .Values.config.rds.port }}/{{ .Values.config.rds.database }}?currentSchema={{ .Values.config.rds.schema }}&ssl=true&sslmode=require"
            - name: DATASOURCES_DEFAULT_USERNAME
              value: {{ .Values.config.rds.username }}
            - name: DATASOURCES_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.config.rds.passwordSecretKey }}
                  name: {{ .Values.config.rds.passwordSecretName }}
          ports:
            - name: http
              containerPort: {{ .Values.env.SERVER_PORT }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          startupProbe:
            httpGet:
              path: /ping/nothing
              port: {{ .Values.env.SERVER_PORT }}
            failureThreshold: 30
            periodSeconds: 5
          livenessProbe:
            failureThreshold: 6
            successThreshold: 1
            periodSeconds: 30
            timeoutSeconds: 30
            httpGet:
              path: /ping/nothing
              port: {{ .Values.env.SERVER_PORT }}
          readinessProbe:
            failureThreshold: 1
            successThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 5
            httpGet:
              path: /ping/nothing
              port: {{ .Values.env.SERVER_PORT }}