# Default values for user-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: startupbuilder/miiingle-net-user-api
  pullPolicy: IfNotPresent
  tag: "latest"

datasource:
  secretName: "miiingle.dev.secrets"
  maxPoolSize: 10

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""