image:
  repository: "<required value>"
  tag: "latest"
  pullPolicy: Always

replicaCount: 1

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 1024Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 30
  targetCPUUtilizationPercentage: 15
  targetMemoryUtilizationPercentage: 50

config:
  rds:
    host: localhost
    port: 5432
    database: postgres
    schema: public
    username: postgres
    passwordSecretName: rds-secret-name
    passwordSecretKey: password

env:
  SERVER_PORT: "8080"
  TRACING_ZIPKIN_HTTP_URL: "http://zipkin-service.default:9411"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""