apiVersion: apps/v1
kind: Deployment
metadata:
  name: miiingle-user-api
  labels:
    app: miiingle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miiingle
  template:
    metadata:
      labels:
        app: miiingle
    spec:
      containers:
#      - name: zipkin
#        image: openzipkin/zipkin:latest
#        imagePullPolicy: Always
      - name: zipkin
        image: openzipkin/zipkin-aws:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: STORAGE_TYPE
            value: xray
          - name: AWS_XRAY_DAEMON_ADDRESS
            value: "xray-service.default:2000"
          - name: LOGGING_LEVEL_ZIPKIN
            value: DEBUG
        ports:
        - name: http
          containerPort: 9411
          protocol: TCP
      - name: application
        image: startupbuilder/miiingle-net-user-api:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: DATASOURCES_DEFAULT_URL
            valueFrom:
              secretKeyRef:
                key: rds_url
                name: miiingle.dev.secrets
          - name: DATASOURCES_DEFAULT_USERNAME
            valueFrom:
              secretKeyRef:
                key: rds_username
                name: miiingle.dev.secrets
          - name: DATASOURCES_DEFAULT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: rds_password
                name: miiingle.dev.secrets
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          failureThreshold: 6
          successThreshold: 1
          periodSeconds: 30
          timeoutSeconds: 30
          httpGet:
            path: /health
            port: 8080
        readinessProbe:
          failureThreshold: 1
          successThreshold: 1
          periodSeconds: 10
          timeoutSeconds: 5
          httpGet:
            path: /health
            port: 8080